name: 서버배포

# main 브랜치에 푸시될 때 워크플로우 실행
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 물리서버에 echo 출력
    runs-on: self-hosted

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 전체 git 히스토리를 가져와서 차이점을 감지

      # 2. SSH 설정 (SSH 비밀 키를 사용하여 접속 설정)
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. rsync를 통한 파일 동기화 및 서버로 전송
      - name: Sync files to server using rsync
        run: |
          rsync -avz --exclude='.git' --delete -e 'ssh -p 7777 -o StrictHostKeyChecking=no' ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/jjj/dev/next-blog


      # 3. 서버에 변경된 파일 전송
      - name: Sync files to server using rsync
        run: |
          rsync -avz --exclude='.git' --exclude='node_modules' --delete -e 'ssh -p 7777 -o StrictHostKeyChecking=no' ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/jjj/dev/next-blog


