name: 우분투서버 배포

# main브랜치에 푸시될때 자동으로 실행
on:
  push:
    branches:
      - main

jobs:
  test :
    name : 셀프호스팅러너 테스트
    runs-on: self-hosted

    steps:
      - name: Test1
        run : echo "연결되었나요?"

  deploy:
    name: 물리서버 배포
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. 원격 서버에 명령 실행
      - name: Run commands on remote server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}  # 서버 IP 주소
          username: ${{ secrets.SERVER_USER }}  # SSH 사용자명
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH 비밀키
          port: 7777  # SSH 포트
          script: |
            # 변경된 코드 반영 및 재배포
            cd /home/jjj/dev/next-blog

            # 기존 프로세스 종료
            echo "Checking for process using port 3000..."
            pid=$(ss -ltnp | grep ':3000' | awk '{print $6}' | cut -d',' -f2 | cut -d'=' -f2)

            if [ -n "$pid" ]; then
              echo "Killing process on port 3000 with PID: $pid"
              kill -9 $pid
            else
              echo "No process found on port 3000."
            fi

            # 기존 빌드 폴더 삭제
            echo "Removing previous build files..."
            rm -rf .next

            # 프로젝트 빌드 및 배포
            echo "Installing dependencies and building the project..."
            npm install
            npm run build

            # 새로 빌드된 서버 실행
            echo "Starting Next.js server..."
            nohup npm start &