name: 우분투서버 배포

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 물리서버 무중단 배포
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync files to server using rsync
        run: |
          rsync -avz --exclude='.git' --delete -e 'ssh -p 7777 -o StrictHostKeyChecking=no' ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/jjj/dev/next-blog

      - name: Build and deploy using PM2
        run: |
          ssh -p 7777 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
            # PM2 경로 명시적으로 설정
            export PATH=\$PATH:/home/jjj/.nvm/versions/node/v20.17.0/bin

            cd /home/jjj/dev/next-blog

            # 패키지 설치 및 빌드
            echo "Installing dependencies..."
            npm install

            echo "Building the project..."
            npm run build

            # 기존 .next 폴더 백업
            echo "Backing up the current .next folder..."
            mv .next .next_backup || echo "No .next folder to backup"

            # 빌드된 새로운 .next 폴더로 교체
            echo "Replacing the .next folder with the new build..."
            mv .next_backup .next || echo "No .next folder created"

            # PM2로 서버 실행 또는 재시작
            echo "Starting or reloading the application with PM2..."
            /home/jjj/.nvm/versions/node/v20.17.0/bin/pm2 start npm --name "next-blog" -- start || /home/jjj/.nvm/versions/node/v20.17.0/bin/pm2 reload "next-blog"

            # PM2 프로세스 리스트 저장
            echo "Saving PM2 process list..."
            /home/jjj/.nvm/versions/node/v20.17.0/bin/pm2 save

            # 백업 폴더 삭제
            echo "Cleaning up old .next backup..."
            rm -rf .next_backup
          EOF
