name: 우분투서버 배포

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 물리서버 무중단 배포
    runs-on: self-hosted

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. SSH 설정
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. 서버에 변경된 파일 전송
      - name: Sync files to server using rsync
        run: |
          rsync -avz --exclude='.git' --delete -e 'ssh -p 7777 -o StrictHostKeyChecking=no' ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/jjj/dev/next-blog

      # 4. 서버에서 PM2를 사용한 빌드 및 무중단 배포
      - name: Build and deploy using PM2
        run: |
          ssh -p 7777 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
          
            # PM2 경로 명시적으로 설정
            export PATH=\$PATH:/home/jjj/.nvm/versions/node/v20.17.0/bin

            cd /home/jjj/dev/next-blog

            # 3000번 포트를 사용하는 프로세스 종료 (ss 명령어 사용)
            echo "Checking for process using port 3000..."
            pid=\$(ss -ltnp | grep ':3000' | awk '{print \$6}' | cut -d',' -f2 | cut -d'=' -f2)

            if [ -n "\$pid" ]; then
              echo "Killing process on port 3000 with PID: \$pid"
              kill -9 \$pid
            else
              echo "No process found on port 3000."
            fi

            # 기존 .next 폴더 삭제
            echo "Removing the previous .next folder..."
            rm -rf .next

            # 패키지 설치 및 빌드
            echo "Installing dependencies..."
            npm install

            echo "Building the project..."
            npm run build -- --clean

            # PM2로 서버 실행 또는 재시작
            echo "Starting or reloading the application with PM2..."
            pm2 start npm --name "next-blog" -- start || pm2 reload "next-blog"

            # PM2 프로세스 리스트 저장
            echo "Saving PM2 process list..."
            pm2 save
          EOF
