name: 우분투서버 배포

# main브랜치에 푸시될때 자동으로 실행
on:
  push:
    branches:
      - main

jobs:
  test :
    name : 셀프호스팅러너 테스트
    runs-on: self-hosted

    steps:
      - name: Test1
        run : echo "연결되었나요?"
