name: 우분투서버 배포

# main브랜치에 푸시될때 자동으로 실행
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 물리서버 무중단 배포
    runs-on: self-hosted

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 전체 git 히스토리를 가져와서 차이점을 감지

      # 2. SSH를 통한 변경된 파일 전송
      - name: Sync files to server using rsync
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          port: 7777
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rsync -avz --exclude='.git' --delete ./ /home/jjj/dev/next-blog

      # 3. 서버에서 PM2를 사용한 빌드 및 무중단 배포
      - name: Build and deploy using PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          port: 7777
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/jjj/dev/next-blog
            echo "Installing dependencies..."
            npm install

            echo "Building the project..."
            npm run build

            echo "Starting or reloading the application with PM2..."
            pm2 start npm --name "next-blog" -- start || pm2 reload "next-blog"

            echo "Saving PM2 process list..."
            pm2 save