name: 우분투서버 배포

# main 브랜치에 푸시될 때 자동으로 실행
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 물리서버 무중단 배포
    runs-on: self-hosted

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 전체 git 히스토리를 가져와서 차이점을 감지

      # 2. SSH 설정 (SSH 비밀 키를 사용하여 접속 설정)
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. 변경된 파일 전송 (rsync를 사용하여 SSH를 통해 파일 동기화)
      - name: Sync files to server using rsync
        run: |
          rsync -avz --exclude='.git' --delete -e 'ssh -p 7777 -o StrictHostKeyChecking=no' ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/jjj/dev/next-blog

      # 4. 서버에서 PM2를 사용한 빌드 및 무중단 배포
      - name: Build and deploy using PM2
        run: |
          ssh -p 7777 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
          
            source ~/.bashrc   # 환경 변수 로드
          
            # PM2가 설치된 경로를 환경 변수로 설정
            export PATH=\$PATH:/usr/local/bin 
          
            cd /home/jjj/dev/next-blog
          
            # 패키지 설치 및 빌드
            echo "Installing dependencies..."
            npm install

            echo "Building the project..."
            npm run build

            # PM2로 서버 실행 또는 재시작
            echo "Starting or reloading the application with PM2..."
            pm2 start npm --name "next-blog" -- start || pm2 reload "next-blog"

            # PM2 프로세스 리스트 저장
            echo "Saving PM2 process list..."
            pm2 save
          EOF
