name: Echo to physical server

# main 브랜치에 푸시될 때 워크플로우 실행
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 물리서버에 echo 출력
    runs-on: self-hosted

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. SSH 설정 (SSH 비밀 키를 사용하여 접속 설정)
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. 물리서버에 SSH 접속 후 echo 메시지 출력
      - name: Echo message on the server
        run: |
          ssh -p 7777 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
            echo "This is a test message from GitHub Actions!"
          EOF
